language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7-dev

cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
    - $HOME/.cache/matplotlib

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libblas-dev liblapack-dev

# Install packages
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel setuptools
  - pip install --upgrade matplotlib
  - pip install --upgrade scipy
  - pip install --upgrade xlsxwriter
  - pip install --upgrade coveralls
  - python setup.py install

script:
  - source activate $TRAVIS_PYTHON_VERSION
  - nosetests --with-doctest --with-coverage --cover-tests --cover-package=tstoolbox --cover-branches --cover-erase

after_success:
  - coveralls
